version: '3'
services:
  app:
    build: .
    container_name: react-container
    ports:
      - "3000:3000"
    deploy:
      resources:
        reservations:
          cpus: '0.1'
          memory: 16M
        limits:
          cpus: '0.33'
          memory: 64M